server.port: 1111
 
logging: 
    level:
      com.xutj: debug
    file: logs/eurekaServer.log
 
#jasypt 加密
#jasypt.encryptor.password: xutj

eureka: 
    instance: 
       hostname: localhost
       preferIPAddress: true          #优先使用IP地址作为主机名的标识 
       instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port} #修改instanceId
    client: 
       # register-with-eureka: false  #默认为true, 向注册中心注册自己
       # fetch-registry: false          #false表示不向注册中心检索服务信息
       serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
        enable-self-preservation: false #关闭eureka的保护机制，以确保注册中心可以将不可以的实例正确剔除(本地开发、调试的时候设置)
       

spring: 
    application:
       name: eureka-server

info:
    app:  
        name: "@project.name@"
        description: "@project.description@"  
        version: "@project.version@"  
        spring-boot-version: "@project.parent.version@"